version: '3.1'
services:

  db_test:
    image: postgres:10-alpine
    env_file:
      - "./.test.env"

  api_test:
    build: ./api
    command: > 
      bash -c 'node_modules/.bin/wait-port db_test:5432
      && node_modules/.bin/knex migrate:rollback
      && node_modules/.bin/knex migrate:latest
      && node_modules/.bin/knex seed:run
      && npm run tests'
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db_test
    env_file:
      - "./.test.env"