version: '3.1'
services:

  db:
    image: postgres:10-alpine
    env_file:
      - "./.env.docker"
    restart: always
    ports:
      - "5432:5432"

  api:
    build: ./api
    command: sh -c './node_modules/.bin/wait-port db:5432 && node_modules/.bin/knex migrate:latest && node_modules/.bin/knex seed:run && node_modules/.bin/nodemon'
    volumes:
      - ./api:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - "./.env.docker"
    restart: always

  front:
    build: './front'
    command: sh -c 'npm run serve'
    volumes:
      - ./front:/usr/src/app
    ports:
      - "8080:8080"
    restart: always